//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Community.PowerToys.Run.Plugin.Everything.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Community.PowerToys.Run.Plugin.Everything.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Copy value (Ctrl+C) 的本地化字符串。
        /// </summary>
        internal static string Microsoft_plugin_timedate_CopyToClipboard {
            get {
                return ResourceManager.GetString("Microsoft_plugin_timedate_CopyToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Can&apos;t delete {0} 的本地化字符串。
        /// </summary>
        internal static string wox_plugin_everything_canot_delete {
            get {
                return ResourceManager.GetString("wox_plugin_everything_canot_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Can’t start {0} 的本地化字符串。
        /// </summary>
        internal static string wox_plugin_everything_canot_start {
            get {
                return ResourceManager.GetString("wox_plugin_everything_canot_start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copied 的本地化字符串。
        /// </summary>
        internal static string wox_plugin_everything_copied {
            get {
                return ResourceManager.GetString("wox_plugin_everything_copied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copy 的本地化字符串。
        /// </summary>
        internal static string wox_plugin_everything_copy {
            get {
                return ResourceManager.GetString("wox_plugin_everything_copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copy path 的本地化字符串。
        /// </summary>
        internal static string wox_plugin_everything_copy_path {
            get {
                return ResourceManager.GetString("wox_plugin_everything_copy_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete 的本地化字符串。
        /// </summary>
        internal static string wox_plugin_everything_delete {
            get {
                return ResourceManager.GetString("wox_plugin_everything_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Editor Path 的本地化字符串。
        /// </summary>
        internal static string wox_plugin_everything_editor_path {
            get {
                return ResourceManager.GetString("wox_plugin_everything_editor_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Everything Client is not running 的本地化字符串。
        /// </summary>
        internal static string wox_plugin_everything_is_not_running {
            get {
                return ResourceManager.GetString("wox_plugin_everything_is_not_running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open parent folder 的本地化字符串。
        /// </summary>
        internal static string wox_plugin_everything_open_containing_folder {
            get {
                return ResourceManager.GetString("wox_plugin_everything_open_containing_folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open with {0} 的本地化字符串。
        /// </summary>
        internal static string wox_plugin_everything_open_with_editor {
            get {
                return ResourceManager.GetString("wox_plugin_everything_open_with_editor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Search on-disk files using Everything 的本地化字符串。
        /// </summary>
        internal static string wox_plugin_everything_plugin_description {
            get {
                return ResourceManager.GetString("wox_plugin_everything_plugin_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Everything 的本地化字符串。
        /// </summary>
        internal static string wox_plugin_everything_plugin_name {
            get {
                return ResourceManager.GetString("wox_plugin_everything_plugin_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error while querying Everything 的本地化字符串。
        /// </summary>
        internal static string wox_plugin_everything_query_error {
            get {
                return ResourceManager.GetString("wox_plugin_everything_query_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use search result&apos;s location as executable working directory 的本地化字符串。
        /// </summary>
        internal static string wox_plugin_everything_use_location_as_working_dir {
            get {
                return ResourceManager.GetString("wox_plugin_everything_use_location_as_working_dir", resourceCulture);
            }
        }
    }
}
